/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lab6p2_serliogiron;

import java.awt.Color;
import java.util.ArrayList;
import javax.swing.JColorChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author usuario
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        admin_frame = new javax.swing.JFrame();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        Items = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla_items = new javax.swing.JTable();
        label = new javax.swing.JLabel();
        label2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Tipo_items_ComboBox = new javax.swing.JComboBox<>();
        Guardar_items_boton = new javax.swing.JButton();
        Precio_field_items = new javax.swing.JFormattedTextField();
        nombre_items_textfield = new javax.swing.JTextField();
        Casa = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabla_casa = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        casa_nombre_field = new javax.swing.JTextField();
        casa_tamano_field = new javax.swing.JFormattedTextField();
        casa_costo_field = new javax.swing.JFormattedTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        casa_x_field = new javax.swing.JFormattedTextField();
        casa_y_field = new javax.swing.JFormattedTextField();
        guardar_casa_boton = new javax.swing.JButton();
        Puffles = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tabla_puffles = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        guardar_puffles = new javax.swing.JButton();
        puffles_nombre_field = new javax.swing.JTextField();
        puffles_precio_field = new javax.swing.JFormattedTextField();
        boton_color = new javax.swing.JButton();
        Juego = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        juego_nombre = new javax.swing.JTextField();
        juego_costo = new javax.swing.JFormattedTextField();
        juego_recompensa = new javax.swing.JFormattedTextField();
        juego_probabilidad = new javax.swing.JFormattedTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        juego_tabla = new javax.swing.JTable();
        usuario_frame = new javax.swing.JFrame();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        usuario_items = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        usuario_items_tabla_left = new javax.swing.JTable();
        Comprar = new javax.swing.JButton();
        jScrollPane6 = new javax.swing.JScrollPane();
        usuario_tabla = new javax.swing.JTable();
        usuario_casa = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane7 = new javax.swing.JScrollPane();
        usuario_tabla_casas = new javax.swing.JTable();
        ususario_Micasa = new javax.swing.JPanel();
        jScrollPane8 = new javax.swing.JScrollPane();
        usuario_tabla_micasa_left = new javax.swing.JTable();
        boton_comprar_micasa = new javax.swing.JButton();
        jScrollPane9 = new javax.swing.JScrollPane();
        usuario_tabla_micasa_right = new javax.swing.JTable();
        usuario_Juego = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        nombre_field = new javax.swing.JTextField();
        entrar_boton = new javax.swing.JButton();
        contra_field = new javax.swing.JPasswordField();

        tabla_items.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Tipo", "Precio"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabla_items);

        label.setText("Nombre");

        label2.setText("Precio");

        jLabel4.setText("Tipo");

        Tipo_items_ComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sombrero", "Gafa", "Bufanda", "Chaqueta", "Pantalon", "Zapato" }));

        Guardar_items_boton.setText("Guardar");
        Guardar_items_boton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Guardar_items_botonMouseClicked(evt);
            }
        });
        Guardar_items_boton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Guardar_items_botonActionPerformed(evt);
            }
        });

        Precio_field_items.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));

        javax.swing.GroupLayout ItemsLayout = new javax.swing.GroupLayout(Items);
        Items.setLayout(ItemsLayout);
        ItemsLayout.setHorizontalGroup(
            ItemsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ItemsLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70)
                .addGroup(ItemsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ItemsLayout.createSequentialGroup()
                        .addComponent(Guardar_items_boton, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(ItemsLayout.createSequentialGroup()
                        .addGroup(ItemsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label)
                            .addComponent(label2)
                            .addComponent(jLabel4)
                            .addComponent(Tipo_items_ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Precio_field_items)
                            .addComponent(nombre_items_textfield, javax.swing.GroupLayout.DEFAULT_SIZE, 222, Short.MAX_VALUE))
                        .addGap(100, 100, 100))))
        );
        ItemsLayout.setVerticalGroup(
            ItemsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ItemsLayout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(ItemsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(ItemsLayout.createSequentialGroup()
                        .addComponent(label)
                        .addGap(18, 18, 18)
                        .addComponent(nombre_items_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(label2)
                        .addGap(18, 18, 18)
                        .addComponent(Precio_field_items, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Tipo_items_ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(45, 45, 45)
                .addComponent(Guardar_items_boton)
                .addContainerGap(45, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Items", Items);

        tabla_casa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Tamaño", "Costo", "X", "Y"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Double.class, java.lang.Double.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tabla_casa);

        jLabel5.setText("Nombre");

        jLabel6.setText("Tamaño");

        jLabel7.setText("Costo");

        casa_nombre_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                casa_nombre_fieldActionPerformed(evt);
            }
        });

        casa_tamano_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                casa_tamano_fieldActionPerformed(evt);
            }
        });

        jLabel8.setText("X");

        jLabel9.setText("Y");

        casa_x_field.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));

        casa_y_field.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        casa_y_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                casa_y_fieldActionPerformed(evt);
            }
        });

        guardar_casa_boton.setText("Guardar");
        guardar_casa_boton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                guardar_casa_botonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout CasaLayout = new javax.swing.GroupLayout(Casa);
        Casa.setLayout(CasaLayout);
        CasaLayout.setHorizontalGroup(
            CasaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CasaLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(CasaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(CasaLayout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(casa_x_field, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel9))
                    .addGroup(CasaLayout.createSequentialGroup()
                        .addGroup(CasaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(casa_nombre_field, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32)
                        .addGroup(CasaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(casa_tamano_field, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(CasaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CasaLayout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(CasaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(casa_costo_field, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(CasaLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(casa_y_field, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)
                        .addComponent(guardar_casa_boton)))
                .addContainerGap(217, Short.MAX_VALUE))
            .addGroup(CasaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CasaLayout.createSequentialGroup()
                    .addContainerGap(105, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(105, Short.MAX_VALUE)))
        );
        CasaLayout.setVerticalGroup(
            CasaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CasaLayout.createSequentialGroup()
                .addContainerGap(256, Short.MAX_VALUE)
                .addGroup(CasaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(CasaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(casa_nombre_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(casa_tamano_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(casa_costo_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(CasaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(casa_x_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(casa_y_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(guardar_casa_boton))
                .addGap(25, 25, 25))
            .addGroup(CasaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CasaLayout.createSequentialGroup()
                    .addContainerGap(12, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(159, Short.MAX_VALUE)))
        );

        jTabbedPane1.addTab("Casa", Casa);

        tabla_puffles.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Color", "Precio"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Object.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tabla_puffles);

        jLabel10.setText("Nombre");

        jLabel11.setText("Color");

        jLabel12.setText("Precio");

        guardar_puffles.setText("Guardar");
        guardar_puffles.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                guardar_pufflesMouseClicked(evt);
            }
        });
        guardar_puffles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardar_pufflesActionPerformed(evt);
            }
        });

        puffles_precio_field.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));

        boton_color.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                boton_colorMouseClicked(evt);
            }
        });
        boton_color.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_colorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PufflesLayout = new javax.swing.GroupLayout(Puffles);
        Puffles.setLayout(PufflesLayout);
        PufflesLayout.setHorizontalGroup(
            PufflesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PufflesLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(guardar_puffles)
                .addGap(74, 74, 74))
            .addGroup(PufflesLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(79, 79, 79)
                .addGroup(PufflesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PufflesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel12)
                        .addComponent(jLabel10)
                        .addComponent(jLabel11)
                        .addComponent(puffles_nombre_field, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)
                        .addComponent(puffles_precio_field))
                    .addComponent(boton_color, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(168, Short.MAX_VALUE))
        );
        PufflesLayout.setVerticalGroup(
            PufflesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PufflesLayout.createSequentialGroup()
                .addGroup(PufflesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PufflesLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PufflesLayout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(puffles_nombre_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44)
                        .addComponent(jLabel11)
                        .addGap(18, 18, 18)
                        .addComponent(boton_color, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(9, 9, 9)
                .addComponent(jLabel12)
                .addGap(18, 18, 18)
                .addComponent(puffles_precio_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addComponent(guardar_puffles)
                .addGap(44, 44, 44))
        );

        jTabbedPane1.addTab("Puffles", Puffles);

        jLabel13.setText("Nombre");

        jLabel14.setText("Costo");

        jLabel15.setText("Recompensa");

        jLabel16.setText("Porbabilildada de Exito");

        jButton1.setText("Crear");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        juego_costo.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));

        juego_recompensa.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));

        juego_probabilidad.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));

        juego_tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Costo", "Recompensa", "Porcentaje"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Double.class, java.lang.Double.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(juego_tabla);

        javax.swing.GroupLayout JuegoLayout = new javax.swing.GroupLayout(Juego);
        Juego.setLayout(JuegoLayout);
        JuegoLayout.setHorizontalGroup(
            JuegoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JuegoLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 91, Short.MAX_VALUE)
                .addGroup(JuegoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel15)
                    .addComponent(jLabel14)
                    .addComponent(jLabel13)
                    .addComponent(jLabel16)
                    .addComponent(juego_costo)
                    .addComponent(juego_recompensa)
                    .addComponent(juego_probabilidad, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE)
                    .addComponent(jButton1)
                    .addComponent(juego_nombre))
                .addGap(75, 75, 75))
        );
        JuegoLayout.setVerticalGroup(
            JuegoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JuegoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(JuegoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(JuegoLayout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addGap(15, 15, 15)
                        .addComponent(juego_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel14)
                        .addGap(18, 18, 18)
                        .addComponent(juego_costo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23)
                        .addComponent(jLabel15)
                        .addGap(18, 18, 18)
                        .addComponent(juego_recompensa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel16)
                        .addGap(18, 18, 18)
                        .addComponent(juego_probabilidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Juego", Juego);

        javax.swing.GroupLayout admin_frameLayout = new javax.swing.GroupLayout(admin_frame.getContentPane());
        admin_frame.getContentPane().setLayout(admin_frameLayout);
        admin_frameLayout.setHorizontalGroup(
            admin_frameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(admin_frameLayout.createSequentialGroup()
                .addGap(152, 152, 152)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 536, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(142, Short.MAX_VALUE))
        );
        admin_frameLayout.setVerticalGroup(
            admin_frameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(admin_frameLayout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 392, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(71, Short.MAX_VALUE))
        );

        usuario_items_tabla_left.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Tipo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane5.setViewportView(usuario_items_tabla_left);

        Comprar.setText("Comprar");
        Comprar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ComprarMouseClicked(evt);
            }
        });

        usuario_tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Precio", "Tipo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Double.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane6.setViewportView(usuario_tabla);

        javax.swing.GroupLayout usuario_itemsLayout = new javax.swing.GroupLayout(usuario_items);
        usuario_items.setLayout(usuario_itemsLayout);
        usuario_itemsLayout.setHorizontalGroup(
            usuario_itemsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(usuario_itemsLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(usuario_itemsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(usuario_itemsLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(usuario_itemsLayout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(Comprar, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(71, Short.MAX_VALUE))))
        );
        usuario_itemsLayout.setVerticalGroup(
            usuario_itemsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(usuario_itemsLayout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addGroup(usuario_itemsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(usuario_itemsLayout.createSequentialGroup()
                        .addComponent(Comprar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(91, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Items", usuario_items);

        jButton2.setText("Comprar Casa");

        jButton3.setText("Vender Casa");

        usuario_tabla_casas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Tamaño", "Costo", "X", "Y"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Double.class, java.lang.Double.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane7.setViewportView(usuario_tabla_casas);

        javax.swing.GroupLayout usuario_casaLayout = new javax.swing.GroupLayout(usuario_casa);
        usuario_casa.setLayout(usuario_casaLayout);
        usuario_casaLayout.setHorizontalGroup(
            usuario_casaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(usuario_casaLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(usuario_casaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 423, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(usuario_casaLayout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addGap(29, 29, 29)
                        .addComponent(jButton3)))
                .addContainerGap(71, Short.MAX_VALUE))
        );
        usuario_casaLayout.setVerticalGroup(
            usuario_casaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(usuario_casaLayout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(usuario_casaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(168, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Casa", usuario_casa);

        usuario_tabla_micasa_left.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Color"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane8.setViewportView(usuario_tabla_micasa_left);

        boton_comprar_micasa.setText("Comprar");
        boton_comprar_micasa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                boton_comprar_micasaMouseClicked(evt);
            }
        });

        usuario_tabla_micasa_right.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Color", "Precio"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Object.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane9.setViewportView(usuario_tabla_micasa_right);

        javax.swing.GroupLayout ususario_MicasaLayout = new javax.swing.GroupLayout(ususario_Micasa);
        ususario_Micasa.setLayout(ususario_MicasaLayout);
        ususario_MicasaLayout.setHorizontalGroup(
            ususario_MicasaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ususario_MicasaLayout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ususario_MicasaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(boton_comprar_micasa, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(98, 98, 98))
        );
        ususario_MicasaLayout.setVerticalGroup(
            ususario_MicasaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ususario_MicasaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(boton_comprar_micasa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(ususario_MicasaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(87, 87, 87))
        );

        jTabbedPane2.addTab("Mi casa", ususario_Micasa);

        javax.swing.GroupLayout usuario_JuegoLayout = new javax.swing.GroupLayout(usuario_Juego);
        usuario_Juego.setLayout(usuario_JuegoLayout);
        usuario_JuegoLayout.setHorizontalGroup(
            usuario_JuegoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 531, Short.MAX_VALUE)
        );
        usuario_JuegoLayout.setVerticalGroup(
            usuario_JuegoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 364, Short.MAX_VALUE)
        );

        jTabbedPane2.addTab("Juego", usuario_Juego);

        javax.swing.GroupLayout usuario_frameLayout = new javax.swing.GroupLayout(usuario_frame.getContentPane());
        usuario_frame.getContentPane().setLayout(usuario_frameLayout);
        usuario_frameLayout.setHorizontalGroup(
            usuario_frameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(usuario_frameLayout.createSequentialGroup()
                .addGap(127, 127, 127)
                .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 536, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(167, Short.MAX_VALUE))
        );
        usuario_frameLayout.setVerticalGroup(
            usuario_frameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(usuario_frameLayout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 392, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(107, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Club Penguin");

        jLabel2.setText("Nombre");

        jLabel3.setText("Contraseña");

        nombre_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombre_fieldActionPerformed(evt);
            }
        });

        entrar_boton.setText("Entrar");
        entrar_boton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                entrar_botonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(125, 125, 125)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(105, 105, 105)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(nombre_field)
                            .addComponent(contra_field, javax.swing.GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(154, 154, 154)
                        .addComponent(entrar_boton)))
                .addContainerGap(98, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nombre_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(contra_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(entrar_boton)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nombre_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombre_fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombre_fieldActionPerformed

    private void entrar_botonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_entrar_botonMouseClicked
        
        String nombre = nombre_field.getText();
        
        String contra = contra_field.getText();

        Penguin p = new Penguin(nombre, contra);
        
        if (p.getNombre().equals("p")) {
            if (p.getContr().equals("p")) {
                JOptionPane.showMessageDialog(this, "Hola Admin");
                admin_frame.pack();
                admin_frame.setVisible(true);
            }
        }else{
            pinguinos.add(p);
            
            JOptionPane.showMessageDialog(this, "Ingresado");
            
            usuario_frame.pack();
            usuario_frame.setVisible(true);
        }
    }//GEN-LAST:event_entrar_botonMouseClicked

    private void Guardar_items_botonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Guardar_items_botonMouseClicked
        DefaultTableModel model = (DefaultTableModel) tabla_items.getModel();
        
        Object[]datos = new Object[3];
        datos [0] = nombre_items_textfield.getText();
        datos [2] = Double.parseDouble(Precio_field_items.getText());
        datos [1] = Tipo_items_ComboBox.getSelectedItem();
        
        model.addRow(datos);
        tabla_items.setModel(model);
        usuario_tabla.setModel(model);
    }//GEN-LAST:event_Guardar_items_botonMouseClicked

    private void casa_nombre_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_casa_nombre_fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_casa_nombre_fieldActionPerformed

    private void casa_tamano_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_casa_tamano_fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_casa_tamano_fieldActionPerformed

    private void casa_y_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_casa_y_fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_casa_y_fieldActionPerformed

    private void guardar_casa_botonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_guardar_casa_botonMouseClicked
        DefaultTableModel model = (DefaultTableModel) tabla_casa.getModel();
        
        Object[]datos = new Object[5];
        
        datos [0] = casa_nombre_field.getText();
        datos [1] = Double.parseDouble(casa_tamano_field.getText());
        datos [2] = Double.parseDouble(casa_costo_field.getText());
        datos [3] = Integer.parseInt(casa_x_field.getText());
        datos [4] = Integer.parseInt(casa_y_field.getText());
        
        model.addRow(datos);
        tabla_casa.setModel(model);
        usuario_tabla_casas.setModel(model);
    }//GEN-LAST:event_guardar_casa_botonMouseClicked

    private void guardar_pufflesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardar_pufflesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_guardar_pufflesActionPerformed

    private void boton_colorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton_colorMouseClicked
        
    }//GEN-LAST:event_boton_colorMouseClicked

    private void boton_colorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_colorActionPerformed
        Color c = JColorChooser.showDialog(null, "Seleccione un color", Color.yellow);
        
        boton_color.setBackground(c);
    }//GEN-LAST:event_boton_colorActionPerformed

    private void guardar_pufflesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_guardar_pufflesMouseClicked
        DefaultTableModel model = (DefaultTableModel) tabla_puffles.getModel();
        
        Object[]datos = new Object[3];
        
        datos [0] = puffles_nombre_field.getText();
        datos [2] = Double.parseDouble(puffles_precio_field.getText());
        datos [1] = boton_color.getBackground();
        
        model.addRow(datos);
        tabla_puffles.setModel(model);
        usuario_tabla_micasa_right.setModel(model);
    }//GEN-LAST:event_guardar_pufflesMouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        //------------------
        
        DefaultTableModel model = (DefaultTableModel) juego_tabla.getModel();
        
        Object[]datos = new Object[4];
        
        datos [0] = juego_nombre.getText();
        datos [1] = Double.parseDouble(juego_costo.getText());
        datos [2] = Double.parseDouble(juego_recompensa.getText());
        datos [3] = Integer.parseInt(juego_probabilidad.getText());
        
        model.addRow(datos);
        juego_tabla.setModel(model);
    }//GEN-LAST:event_jButton1MouseClicked

    private void ComprarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ComprarMouseClicked
        DefaultTableModel model = (DefaultTableModel) usuario_tabla_micasa_left.getModel();
        Object[]datos = new Object[2];
        
        datos [0] = usuario_tabla_micasa_right.getValueAt(usuario_tabla_micasa_right.getSelectedRow(), 0);
        
        datos [1] = usuario_tabla_micasa_right.getValueAt(usuario_tabla_micasa_right.getSelectedRow(), 1);
        
        model.addRow(datos);
        usuario_tabla_micasa_left.setModel(model);
    }//GEN-LAST:event_ComprarMouseClicked

    private void Guardar_items_botonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Guardar_items_botonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Guardar_items_botonActionPerformed

    private void boton_comprar_micasaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton_comprar_micasaMouseClicked
        DefaultTableModel model = (DefaultTableModel) usuario_tabla_micasa_left.getModel();
        
        Object[]datos = new Object[2];
        
        datos [0] = usuario_tabla_micasa_right.getValueAt(usuario_tabla_micasa_right.getSelectedRow(), 0);
        
        datos [1] = usuario_tabla_micasa_right.getValueAt(usuario_tabla_micasa_right.getSelectedRow(), 1);
        
        model.addRow(datos);
        usuario_tabla_micasa_left.setModel(model);
    }//GEN-LAST:event_boton_comprar_micasaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Casa;
    private javax.swing.JButton Comprar;
    private javax.swing.JButton Guardar_items_boton;
    private javax.swing.JPanel Items;
    private javax.swing.JPanel Juego;
    private javax.swing.JFormattedTextField Precio_field_items;
    private javax.swing.JPanel Puffles;
    private javax.swing.JComboBox<String> Tipo_items_ComboBox;
    private javax.swing.JFrame admin_frame;
    private javax.swing.JButton boton_color;
    private javax.swing.JButton boton_comprar_micasa;
    private javax.swing.JFormattedTextField casa_costo_field;
    private javax.swing.JTextField casa_nombre_field;
    private javax.swing.JFormattedTextField casa_tamano_field;
    private javax.swing.JFormattedTextField casa_x_field;
    private javax.swing.JFormattedTextField casa_y_field;
    private javax.swing.JPasswordField contra_field;
    private javax.swing.JButton entrar_boton;
    private javax.swing.JButton guardar_casa_boton;
    private javax.swing.JButton guardar_puffles;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JFormattedTextField juego_costo;
    private javax.swing.JTextField juego_nombre;
    private javax.swing.JFormattedTextField juego_probabilidad;
    private javax.swing.JFormattedTextField juego_recompensa;
    private javax.swing.JTable juego_tabla;
    private javax.swing.JLabel label;
    private javax.swing.JLabel label2;
    private javax.swing.JTextField nombre_field;
    private javax.swing.JTextField nombre_items_textfield;
    private javax.swing.JTextField puffles_nombre_field;
    private javax.swing.JFormattedTextField puffles_precio_field;
    private javax.swing.JTable tabla_casa;
    private javax.swing.JTable tabla_items;
    private javax.swing.JTable tabla_puffles;
    private javax.swing.JPanel usuario_Juego;
    private javax.swing.JPanel usuario_casa;
    private javax.swing.JFrame usuario_frame;
    private javax.swing.JPanel usuario_items;
    private javax.swing.JTable usuario_items_tabla_left;
    private javax.swing.JTable usuario_tabla;
    private javax.swing.JTable usuario_tabla_casas;
    private javax.swing.JTable usuario_tabla_micasa_left;
    private javax.swing.JTable usuario_tabla_micasa_right;
    private javax.swing.JPanel ususario_Micasa;
    // End of variables declaration//GEN-END:variables

    private ArrayList <Penguin> pinguinos = new ArrayList();
}
